export const titleOptions = [
  { value: "all", label: "All" },
  { value: "Addictions Medicine", label: "Addictions Medicine" },
  { value: "Anaesthetics", label: "Anaesthetics" },
  { value: "Anaesthetics - GP", label: "Anaesthetics - GP" },
  { value: "Anaesthetics - General", label: "Anaesthetics - General" },
  { value: "Cancer Services - Medical Oncology", label: "Cancer Services - Medical Oncology" },
  { value: "Cardiology", label: "Cardiology" },
  { value: "Critical Care - Emergency", label: "Critical Care - Emergency" },
  { value: "ED", label: "ED" },
  { value: "Emergency", label: "Emergency" },
  { value: "Emergency Medicine", label: "Emergency Medicine" },
  { value: "General Medicine", label: "General Medicine" },
  { value: "General Practice", label: "General Practice" },
  { value: "General Practice - GP Clinic", label: "General Practice - GP Clinic" },
  { value: "General Practice - Obstetrics", label: "General Practice - Obstetrics" },
  { value: "General Practice - Urgent Care/ Fast Track", label: "General Practice - Urgent Care/ Fast Track" },
  { value: "General Surgery", label: "General Surgery" },
  { value: "General Surgery (Surgery)", label: "General Surgery (Surgery)" },
  { value: "Haematology Oncology", label: "Haematology Oncology" },
  { value: "Hospital in the Home", label: "Hospital in the Home" },
  { value: "ICU", label: "ICU" },
  { value: "Ic (Fast Track Clinic)", label: "Ic (Fast Track Clinic)" },
  { value: "Intensive Care", label: "Intensive Care" },
  { value: "Intensive Care (CCM)", label: "Intensive Care (CCM)" },
  { value: "Intensive Care - General", label: "Intensive Care - General" },
  { value: "Intensive Care Medicine", label: "Intensive Care Medicine" },
  { value: "Medicine - Oncology", label: "Medicine - Oncology" },
  { value: "Medicine - Palliative Care", label: "Medicine - Palliative Care" },
  { value: "Medicine - Rehabilitation", label: "Medicine - Rehabilitation" },
  { value: "MHDA", label: "MHDA" },
  { value: "Psychiatry - Adult", label: "Psychiatry - Adult" },
  { value: "Psychiatry - Child and Adolescent", label: "Psychiatry - Child and Adolescent" },
  { value: "Psychiatry - Community", label: "Psychiatry - Community" },
  { value: "Psychiatry - Community Mental Health", label: "Psychiatry - Community Mental Health" },
  { value: "Psychiatry - General (adults)", label: "Psychiatry - General (adults)" },
  { value: "Psychiatry - General (all ages)", label: "Psychiatry - General (all ages)" },
  { value: "Psychiatry - General Adult", label: "Psychiatry - General Adult" },
  { value: "Psychiatry - General Psychiatry", label: "Psychiatry - General Psychiatry" },
  { value: "Surgery - General", label: "Surgery - General" },
  { value: "Surgery - Orthopaedic", label: "Surgery - Orthopaedic" },
]

export const stateOptions = [
  { value: "all", label: "All" },
  { value: "nsw", label: "NSW" },
  { value: "nt", label: "NT" },
  { value: "qld", label: "QLD" },
  { value: "sa", label: "SA" },
  { value: "tas", label: "TAS" },
  { value: "vic", label: "VIC" },
  { value: "wa", label: "WA" }
]